### ISSUE TITLE
[payment-challenge.md] Gateway failing to create transactions

### ISSUE THREAD

**Issue by gmonnerat** [jusbrasil/careers#21]
I am unable to create transactions. When I try:
```bash
curl -XPOST --header "Content-Type: application/json" -d '{"amount": 100, "creditcard": { "number": 347318440718565, "issuer": "American Express", "expire_month": "03", "expire_year": "2020", "cvv": "012"}}' 'https://gtw1.rafaelverger.com.br/clients/5c715fdc98cb35650ca10fd8/transactions'
```

I have:
```
<pre>TypeError: Expected string input<br> &nbsp; &nbsp;at Object.luhn
```

This is good because CC_NUMBER should be string.

If I try:
```
curl -XPOST --header "Content-Type: application/json" -d '{"amount": 100, "creditcard": { "number": "347318440718565x", "issuer": "American Express", "expire_month": "03", "expire_year": "2020", "cvv": "012"}}' 'https://gtw1.rafaelverger.com.br/clients/5c715fdc98cb35650ca10fd8/transactions'
```

I have:

```
<pre>Error: Body has wrong data: [<br> &nbsp;&quot;instance.creditcard does not conform to the \&quot;cc\&quot; format&quot;,<br> &nbsp;&quot;instance.creditcard.number does not conform to the \&quot;luhn\&quot; format&quot;<br>]
```

Again, this is good because CC_NUMBER is not matching luhn format

But, if try a good CC_NUMBER:

```
curl -XPOST --header "Content-Type: application/json" -d '{"amount": 100, "creditcard": { "number": "347318440718565", "issuer": "American Express", "expire_month": "03", "expire_year": "2020", "cvv": "012"}}' 'https://gtw1.rafaelverger.com.br/clients/5c715fdc98cb35650ca10fd8/transactions'
```

```
<pre>TypeError: Key must be a buffer<br> &nbsp; &nbsp;at TypeError (native)<br> &nbsp; &nbsp;at new Cipher (crypto.js:110:16)<br> &nbsp; &nbsp;at Object.Cipher (crypto.js:107:12)<br> &nbsp; &nbsp;at encryptCC (/home/rafaelverger/gtw1/app/cc.js:14:25)<br> &nbsp; &nbsp;at app.post (/home/rafaelverger/gtw1/app/transactions.js:88:33)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/rafaelverger/gtw1/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/rafaelverger/gtw1/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at /home/rafaelverger/gtw1/server.js:18:7<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/rafaelverger/gtw1/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/rafaelverger/gtw1/node_modules/express/lib/router/route.js:137:13)</pre>
```

The same happens on Gateway 2 to create cards:
```
curl -XPOST --header "Content-Type: application/json" -d '{ "number": "347318440718565", "issuer": "American Express", "expire_month": "03", "expire_year": "2020", "cvv": "012"}' 'https://gtw2.rafaelverger.com.br/clients/5c7036b212ff8265301d64a1/cards'
```

```html
<pre>TypeError: Key must be a buffer<br> &nbsp; &nbsp;at TypeError (native)<br> &nbsp; &nbsp;at new Cipher (crypto.js:110:16)<br> &nbsp; &nbsp;at Object.Cipher (crypto.js:107:12)<br> &nbsp; &nbsp;at encryptCC (/home/rafaelverger/gtw2/app/cc.js:18:25)<br> &nbsp; &nbsp;at app.post (/home/rafaelverger/gtw2/app/cc.js:125:33)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/rafaelverger/gtw2/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/rafaelverger/gtw2/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at /home/rafaelverger/gtw2/server.js:18:7<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/rafaelverger/gtw2/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/rafaelverger/gtw2/node_modules/express/lib/router/route.js:137:13)</pre>
```

**Comment by rafaelverger** [comment]
Nice! I'll take a look in 30min, but I think that this is related to amex cards, perhaps if u try to replace American Express by AMEX and/or fix CVV number to this type of card (amex has 15 cc numbers and 4 CVV numbers).

**Comment by gmonnerat** [comment]
Thanks! I did know that amex has 4 CVV numbers. I generated fake credit cards using [http://card-generator.com/](http://card-generator.com/)

But, still with AMEX, I have another issue:

```bash
➜  ~ curl -XPOST --header "Content-Type: application/json" -d '{ "number": "340400231624116", "issuer": "AMEX", "expire_month": "09", "expire_year": "2020", "cvv": "6690"}' 'https://gtw2.rafaelverger.com.br/clients/5c7036b212ff8265301d64a1/cards'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Body has wrong data: [<br> &nbsp;&quot;instance does not conform to the \&quot;cc\&quot; format&quot;<br>]<br> &nbsp; &nbsp;at /home/rafaelverger/gtw2/server.js:16:21<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/rafaelverger/gtw2/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/rafaelverger/gtw2/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/home/rafaelverger/gtw2/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/rafaelverger/gtw2/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /home/rafaelverger/gtw2/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at param (/home/rafaelverger/gtw2/node_modules/express/lib/router/index.js:354:14)<br> &nbsp; &nbsp;at param (/home/rafaelverger/gtw2/node_modules/express/lib/router/index.js:365:14)<br> &nbsp; &nbsp;at Function.process_params (/home/rafaelverger/gtw2/node_modules/express/lib/router/index.js:410:3)<br> &nbsp; &nbsp;at next (/home/rafaelverger/gtw2/node_modules/express/lib/router/index.js:275:10)</pre>
</body>
</html>
```
And with VISA:

```bash
➜  ~ curl -XPOST --header "Content-Type: application/json" -d '{ "number": "4916448960785372", "issuer": "VISA", "expire_month": "05", "expire_year": "2019", "cvv": "922"}' 'https://gtw2.rafaelverger.com.br/clients/5c7036b212ff8265301d64a1/cards'

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Key must be a buffer<br> &nbsp; &nbsp;at TypeError (native)<br> &nbsp; &nbsp;at new Cipher (crypto.js:110:16)<br> &nbsp; &nbsp;at Object.Cipher (crypto.js:107:12)<br> &nbsp; &nbsp;at encryptCC (/home/rafaelverger/gtw2/app/cc.js:18:25)<br> &nbsp; &nbsp;at app.post (/home/rafaelverger/gtw2/app/cc.js:125:33)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/rafaelverger/gtw2/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/rafaelverger/gtw2/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at /home/rafaelverger/gtw2/server.js:18:7<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/rafaelverger/gtw2/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/rafaelverger/gtw2/node_modules/express/lib/router/route.js:137:13)</pre>
</body>
</html>
```

Do you have the logic used to validate CCs? Maybe I am missing something.

**Comment by rafaelverger** [comment]
It should be a simple lunh valuation...  At the end of validation I compare the expected issuer with the one u've sent...

**Comment by gmonnerat** [comment]
I see.
I think lunh validaion is working fine.

"4916448960785372" is good and "4916448960785371" is bad.

```bash
➜  ~ curl -XPOST --header "Content-Type: application/json" -d '{ "number": "4916448960785371", "issuer": "VISA", "expire_month": "05", "expire_year": "2019", "cvv": "922"}' 'https://gtw2.rafaelverger.com.br/clients/5c7036b212ff8265301d64a1/cards'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Body has wrong data: [<br> &nbsp;&quot;instance.number does not conform to the \&quot;luhn\&quot; format&quot;<br>]<br> &nbsp; &nbsp;at /home/rafaelverger/gtw2/server.js:16:21<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/rafaelverger/gtw2/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/rafaelverger/gtw2/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/home/rafaelverger/gtw2/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/rafaelverger/gtw2/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /home/rafaelverger/gtw2/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at param (/home/rafaelverger/gtw2/node_modules/express/lib/router/index.js:354:14)<br> &nbsp; &nbsp;at param (/home/rafaelverger/gtw2/node_modules/express/lib/router/index.js:365:14)<br> &nbsp; &nbsp;at Function.process_params (/home/rafaelverger/gtw2/node_modules/express/lib/router/index.js:410:3)<br> &nbsp; &nbsp;at next (/home/rafaelverger/gtw2/node_modules/express/lib/router/index.js:275:10)</pre>
</body>
</html>

➜  ~ curl -XPOST --header "Content-Type: application/json" -d '{ "number": "4916448960785372", "issuer": "VISA", "expire_month": "05", "expire_year": "2019", "cvv": "922"}' 'https://gtw2.rafaelverger.com.br/clients/5c7036b212ff8265301d64a1/cards'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: Key must be a buffer<br> &nbsp; &nbsp;at TypeError (native)<br> &nbsp; &nbsp;at new Cipher (crypto.js:110:16)<br> &nbsp; &nbsp;at Object.Cipher (crypto.js:107:12)<br> &nbsp; &nbsp;at encryptCC (/home/rafaelverger/gtw2/app/cc.js:18:25)<br> &nbsp; &nbsp;at app.post (/home/rafaelverger/gtw2/app/cc.js:125:33)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/rafaelverger/gtw2/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/rafaelverger/gtw2/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at /home/rafaelverger/gtw2/server.js:18:7<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/rafaelverger/gtw2/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/rafaelverger/gtw2/node_modules/express/lib/router/route.js:137:13)</pre>
</body>
</html>
```

Just curious, if possible, what is done in /home/rafaelverger/gtw2/app/cc.js:18 ? Maybe can help me 😄

**Comment by rafaelverger** [comment]
Hmm... the first POST request (creating CC into GTW2) is really wrong... lunh check fails for this number: `4916448960785371`.. I've triple checked with another services (like https://www.validcreditcardnumber.com)

**Comment by rafaelverger** [comment]
The second error was due to a wrong config key in the server... apparently the "keep-running" process has some issue.
